export const CITY_CATALOG = [
  { key: "vancouver", name: "Vancouver", region: "Canada", timeZone: "America/Vancouver" },
  { key: "toronto", name: "Toronto", region: "Canada", timeZone: "America/Toronto" },
  { key: "montreal", name: "Montreal", region: "Canada", timeZone: "America/Toronto" },
  { key: "ottawa", name: "Ottawa", region: "Canada", timeZone: "America/Toronto" },
  { key: "winnipeg", name: "Winnipeg", region: "Canada", timeZone: "America/Winnipeg" },
  { key: "calgary", name: "Calgary", region: "Canada", timeZone: "America/Edmonton" },
  { key: "new-york", name: "New York", region: "United States", timeZone: "America/New_York" },
  { key: "boston", name: "Boston", region: "United States", timeZone: "America/New_York" },
  { key: "washington-dc", name: "Washington, D.C.", region: "United States", timeZone: "America/New_York" },
  { key: "miami", name: "Miami", region: "United States", timeZone: "America/New_York" },
  { key: "atlanta", name: "Atlanta", region: "United States", timeZone: "America/New_York" },
  { key: "chicago", name: "Chicago", region: "United States", timeZone: "America/Chicago" },
  { key: "houston", name: "Houston", region: "United States", timeZone: "America/Chicago" },
  { key: "denver", name: "Denver", region: "United States", timeZone: "America/Denver" },
  { key: "phoenix", name: "Phoenix", region: "United States", timeZone: "America/Phoenix" },
  { key: "los-angeles", name: "Los Angeles", region: "United States", timeZone: "America/Los_Angeles" },
  { key: "san-francisco", name: "San Francisco", region: "United States", timeZone: "America/Los_Angeles" },
  { key: "seattle", name: "Seattle", region: "United States", timeZone: "America/Los_Angeles" },
  { key: "honolulu", name: "Honolulu", region: "United States", timeZone: "Pacific/Honolulu" },
  { key: "anchorage", name: "Anchorage", region: "United States", timeZone: "America/Anchorage" },
  { key: "mexico-city", name: "Mexico City", region: "Mexico", timeZone: "America/Mexico_City" },
  { key: "guadalajara", name: "Guadalajara", region: "Mexico", timeZone: "America/Mexico_City" },
  { key: "monterrey", name: "Monterrey", region: "Mexico", timeZone: "America/Monterrey" },
  { key: "tijuana", name: "Tijuana", region: "Mexico", timeZone: "America/Tijuana" },
  { key: "guatemala-city", name: "Guatemala City", region: "Guatemala", timeZone: "America/Guatemala" },
  { key: "san-jose-costa-rica", name: "San José", region: "Costa Rica", timeZone: "America/Costa_Rica" },
  { key: "panama-city", name: "Panama City", region: "Panama", timeZone: "America/Panama" },
  { key: "havana", name: "Havana", region: "Cuba", timeZone: "America/Havana" },
  { key: "sao-paulo", name: "São Paulo", region: "Brazil", timeZone: "America/Sao_Paulo" },
  { key: "buenos-aires", name: "Buenos Aires", region: "Argentina", timeZone: "America/Argentina/Buenos_Aires" },
  { key: "santiago", name: "Santiago", region: "Chile", timeZone: "America/Santiago" },
  { key: "lima", name: "Lima", region: "Peru", timeZone: "America/Lima" },
  { key: "bogota", name: "Bogotá", region: "Colombia", timeZone: "America/Bogota" },
  { key: "caracas", name: "Caracas", region: "Venezuela", timeZone: "America/Caracas" },
  { key: "quito", name: "Quito", region: "Ecuador", timeZone: "America/Guayaquil" },
  { key: "montevideo", name: "Montevideo", region: "Uruguay", timeZone: "America/Montevideo" },
  { key: "london", name: "London", region: "United Kingdom", timeZone: "Europe/London" },
  { key: "dublin", name: "Dublin", region: "Ireland", timeZone: "Europe/Dublin" },
  { key: "lisbon", name: "Lisbon", region: "Portugal", timeZone: "Europe/Lisbon" },
  { key: "madrid", name: "Madrid", region: "Spain", timeZone: "Europe/Madrid" },
  { key: "paris", name: "Paris", region: "France", timeZone: "Europe/Paris" },
  { key: "brussels", name: "Brussels", region: "Belgium", timeZone: "Europe/Brussels" },
  { key: "amsterdam", name: "Amsterdam", region: "Netherlands", timeZone: "Europe/Amsterdam" },
  { key: "berlin", name: "Berlin", region: "Germany", timeZone: "Europe/Berlin" },
  { key: "zurich", name: "Zurich", region: "Switzerland", timeZone: "Europe/Zurich" },
  { key: "rome", name: "Rome", region: "Italy", timeZone: "Europe/Rome" },
  { key: "vienna", name: "Vienna", region: "Austria", timeZone: "Europe/Vienna" },
  { key: "prague", name: "Prague", region: "Czechia", timeZone: "Europe/Prague" },
  { key: "warsaw", name: "Warsaw", region: "Poland", timeZone: "Europe/Warsaw" },
  { key: "stockholm", name: "Stockholm", region: "Sweden", timeZone: "Europe/Stockholm" },
  { key: "oslo", name: "Oslo", region: "Norway", timeZone: "Europe/Oslo" },
  { key: "copenhagen", name: "Copenhagen", region: "Denmark", timeZone: "Europe/Copenhagen" },
  { key: "helsinki", name: "Helsinki", region: "Finland", timeZone: "Europe/Helsinki" },
  { key: "athens", name: "Athens", region: "Greece", timeZone: "Europe/Athens" },
  { key: "istanbul", name: "Istanbul", region: "Turkey", timeZone: "Europe/Istanbul" },
  { key: "bucharest", name: "Bucharest", region: "Romania", timeZone: "Europe/Bucharest" },
  { key: "kyiv", name: "Kyiv", region: "Ukraine", timeZone: "Europe/Kyiv" },
  { key: "moscow", name: "Moscow", region: "Russia", timeZone: "Europe/Moscow" },
  { key: "reykjavik", name: "Reykjavik", region: "Iceland", timeZone: "Atlantic/Reykjavik" },
  { key: "cairo", name: "Cairo", region: "Egypt", timeZone: "Africa/Cairo" },
  { key: "casablanca", name: "Casablanca", region: "Morocco", timeZone: "Africa/Casablanca" },
  { key: "accra", name: "Accra", region: "Ghana", timeZone: "Africa/Accra" },
  { key: "lagos", name: "Lagos", region: "Nigeria", timeZone: "Africa/Lagos" },
  { key: "johannesburg", name: "Johannesburg", region: "South Africa", timeZone: "Africa/Johannesburg" },
  { key: "cape-town", name: "Cape Town", region: "South Africa", timeZone: "Africa/Johannesburg" },
  { key: "nairobi", name: "Nairobi", region: "Kenya", timeZone: "Africa/Nairobi" },
  { key: "addis-ababa", name: "Addis Ababa", region: "Ethiopia", timeZone: "Africa/Addis_Ababa" },
  { key: "dakar", name: "Dakar", region: "Senegal", timeZone: "Africa/Dakar" },
  { key: "dubai", name: "Dubai", region: "United Arab Emirates", timeZone: "Asia/Dubai" },
  { key: "riyadh", name: "Riyadh", region: "Saudi Arabia", timeZone: "Asia/Riyadh" },
  { key: "doha", name: "Doha", region: "Qatar", timeZone: "Asia/Qatar" },
  { key: "kuwait-city", name: "Kuwait City", region: "Kuwait", timeZone: "Asia/Kuwait" },
  { key: "jerusalem", name: "Jerusalem", region: "Israel", timeZone: "Asia/Jerusalem" },
  { key: "tehran", name: "Tehran", region: "Iran", timeZone: "Asia/Tehran" },
  { key: "karachi", name: "Karachi", region: "Pakistan", timeZone: "Asia/Karachi" },
  { key: "delhi", name: "Delhi", region: "India", timeZone: "Asia/Kolkata" },
  { key: "dhaka", name: "Dhaka", region: "Bangladesh", timeZone: "Asia/Dhaka" },
  { key: "kathmandu", name: "Kathmandu", region: "Nepal", timeZone: "Asia/Kathmandu" },
  { key: "colombo", name: "Colombo", region: "Sri Lanka", timeZone: "Asia/Colombo" },
  { key: "bangkok", name: "Bangkok", region: "Thailand", timeZone: "Asia/Bangkok" },
  { key: "jakarta", name: "Jakarta", region: "Indonesia", timeZone: "Asia/Jakarta" },
  { key: "singapore", name: "Singapore", region: "Singapore", timeZone: "Asia/Singapore" },
  { key: "kuala-lumpur", name: "Kuala Lumpur", region: "Malaysia", timeZone: "Asia/Kuala_Lumpur" },
  { key: "manila", name: "Manila", region: "Philippines", timeZone: "Asia/Manila" },
  { key: "hong-kong", name: "Hong Kong", region: "Hong Kong", timeZone: "Asia/Hong_Kong" },
  { key: "taipei", name: "Taipei", region: "Taiwan", timeZone: "Asia/Taipei" },
  { key: "beijing", name: "Beijing", region: "China", timeZone: "Asia/Shanghai" },
  { key: "shanghai", name: "Shanghai", region: "China", timeZone: "Asia/Shanghai" },
  { key: "tokyo", name: "Tokyo", region: "Japan", timeZone: "Asia/Tokyo" },
  { key: "seoul", name: "Seoul", region: "South Korea", timeZone: "Asia/Seoul" },
  { key: "ulaanbaatar", name: "Ulaanbaatar", region: "Mongolia", timeZone: "Asia/Ulaanbaatar" },
  { key: "hanoi", name: "Hanoi", region: "Vietnam", timeZone: "Asia/Ho_Chi_Minh" },
  { key: "ho-chi-minh-city", name: "Ho Chi Minh City", region: "Vietnam", timeZone: "Asia/Ho_Chi_Minh" },
  { key: "sydney", name: "Sydney", region: "Australia", timeZone: "Australia/Sydney" },
  { key: "melbourne", name: "Melbourne", region: "Australia", timeZone: "Australia/Melbourne" },
  { key: "brisbane", name: "Brisbane", region: "Australia", timeZone: "Australia/Brisbane" },
  { key: "adelaide", name: "Adelaide", region: "Australia", timeZone: "Australia/Adelaide" },
  { key: "perth", name: "Perth", region: "Australia", timeZone: "Australia/Perth" },
  { key: "auckland", name: "Auckland", region: "New Zealand", timeZone: "Pacific/Auckland" },
  { key: "port-moresby", name: "Port Moresby", region: "Papua New Guinea", timeZone: "Pacific/Port_Moresby" },
  { key: "suva", name: "Suva", region: "Fiji", timeZone: "Pacific/Fiji" },
  { key: "tirana", name: "Tirana", region: "Albania", timeZone: "Europe/Tirane" },
  { key: "andorra-la-vella", name: "Andorra la Vella", region: "Andorra", timeZone: "Europe/Andorra" },
  { key: "minsk", name: "Minsk", region: "Belarus", timeZone: "Europe/Minsk" },
  { key: "sarajevo", name: "Sarajevo", region: "Bosnia and Herzegovina", timeZone: "Europe/Sarajevo" },
  { key: "sofia", name: "Sofia", region: "Bulgaria", timeZone: "Europe/Sofia" },
  { key: "zagreb", name: "Zagreb", region: "Croatia", timeZone: "Europe/Zagreb" },
  { key: "tallinn", name: "Tallinn", region: "Estonia", timeZone: "Europe/Tallinn" },
  { key: "riga", name: "Riga", region: "Latvia", timeZone: "Europe/Riga" },
  { key: "vilnius", name: "Vilnius", region: "Lithuania", timeZone: "Europe/Vilnius" },
  { key: "luxembourg", name: "Luxembourg", region: "Luxembourg", timeZone: "Europe/Luxembourg" },
  { key: "chisinau", name: "Chisinau", region: "Moldova", timeZone: "Europe/Chisinau" },
  { key: "podgorica", name: "Podgorica", region: "Montenegro", timeZone: "Europe/Podgorica" },
  { key: "skopje", name: "Skopje", region: "North Macedonia", timeZone: "Europe/Skopje" },
  { key: "belgrade", name: "Belgrade", region: "Serbia", timeZone: "Europe/Belgrade" },
  { key: "bratislava", name: "Bratislava", region: "Slovakia", timeZone: "Europe/Bratislava" },
  { key: "ljubljana", name: "Ljubljana", region: "Slovenia", timeZone: "Europe/Ljubljana" },
  { key: "nicosia", name: "Nicosia", region: "Cyprus", timeZone: "Asia/Nicosia" },
  { key: "valletta", name: "Valletta", region: "Malta", timeZone: "Europe/Malta" },
  { key: "san-marino", name: "San Marino", region: "San Marino", timeZone: "Europe/San_Marino" },
  { key: "kabul", name: "Kabul", region: "Afghanistan", timeZone: "Asia/Kabul" },
  { key: "yerevan", name: "Yerevan", region: "Armenia", timeZone: "Asia/Yerevan" },
  { key: "baku", name: "Baku", region: "Azerbaijan", timeZone: "Asia/Baku" },
  { key: "tbilisi", name: "Tbilisi", region: "Georgia", timeZone: "Asia/Tbilisi" },
  { key: "astana", name: "Astana", region: "Kazakhstan", timeZone: "Asia/Almaty" },
  { key: "bishkek", name: "Bishkek", region: "Kyrgyzstan", timeZone: "Asia/Bishkek" },
  { key: "dushanbe", name: "Dushanbe", region: "Tajikistan", timeZone: "Asia/Dushanbe" },
  { key: "ashgabat", name: "Ashgabat", region: "Turkmenistan", timeZone: "Asia/Ashgabat" },
  { key: "tashkent", name: "Tashkent", region: "Uzbekistan", timeZone: "Asia/Tashkent" },
  { key: "baghdad", name: "Baghdad", region: "Iraq", timeZone: "Asia/Baghdad" },
  { key: "amman", name: "Amman", region: "Jordan", timeZone: "Asia/Amman" },
  { key: "beirut", name: "Beirut", region: "Lebanon", timeZone: "Asia/Beirut" },
  { key: "damascus", name: "Damascus", region: "Syria", timeZone: "Asia/Damascus" },
  { key: "muscat", name: "Muscat", region: "Oman", timeZone: "Asia/Muscat" },
  { key: "sanaa", name: "Sana'a", region: "Yemen", timeZone: "Asia/Aden" },
  { key: "male", name: "Malé", region: "Maldives", timeZone: "Indian/Maldives" },
  { key: "thimphu", name: "Thimphu", region: "Bhutan", timeZone: "Asia/Thimphu" },
  { key: "naypyidaw", name: "Naypyidaw", region: "Myanmar", timeZone: "Asia/Yangon" },
  { key: "phnom-penh", name: "Phnom Penh", region: "Cambodia", timeZone: "Asia/Phnom_Penh" },
  { key: "vientiane", name: "Vientiane", region: "Laos", timeZone: "Asia/Vientiane" },
  { key: "bandar-seri-begawan", name: "Bandar Seri Begawan", region: "Brunei", timeZone: "Asia/Brunei" },
  { key: "dili", name: "Dili", region: "Timor-Leste", timeZone: "Asia/Dili" },
  { key: "pyongyang", name: "Pyongyang", region: "North Korea", timeZone: "Asia/Pyongyang" },
  { key: "algiers", name: "Algiers", region: "Algeria", timeZone: "Africa/Algiers" },
  { key: "tunis", name: "Tunis", region: "Tunisia", timeZone: "Africa/Tunis" },
  { key: "tripoli", name: "Tripoli", region: "Libya", timeZone: "Africa/Tripoli" },
  { key: "khartoum", name: "Khartoum", region: "Sudan", timeZone: "Africa/Khartoum" },
  { key: "juba", name: "Juba", region: "South Sudan", timeZone: "Africa/Juba" },
  { key: "djibouti", name: "Djibouti", region: "Djibouti", timeZone: "Africa/Djibouti" },
  { key: "mogadishu", name: "Mogadishu", region: "Somalia", timeZone: "Africa/Mogadishu" },
  { key: "kampala", name: "Kampala", region: "Uganda", timeZone: "Africa/Kampala" },
  { key: "dar-es-salaam", name: "Dar es Salaam", region: "Tanzania", timeZone: "Africa/Dar_es_Salaam" },
  { key: "kigali", name: "Kigali", region: "Rwanda", timeZone: "Africa/Kigali" },
  { key: "bujumbura", name: "Bujumbura", region: "Burundi", timeZone: "Africa/Bujumbura" },
  { key: "kinshasa", name: "Kinshasa", region: "Democratic Republic of the Congo", timeZone: "Africa/Kinshasa" },
  { key: "brazzaville", name: "Brazzaville", region: "Republic of the Congo", timeZone: "Africa/Brazzaville" },
  { key: "luanda", name: "Luanda", region: "Angola", timeZone: "Africa/Luanda" },
  { key: "lusaka", name: "Lusaka", region: "Zambia", timeZone: "Africa/Lusaka" },
  { key: "harare", name: "Harare", region: "Zimbabwe", timeZone: "Africa/Harare" },
  { key: "maputo", name: "Maputo", region: "Mozambique", timeZone: "Africa/Maputo" },
  { key: "windhoek", name: "Windhoek", region: "Namibia", timeZone: "Africa/Windhoek" },
  { key: "gaborone", name: "Gaborone", region: "Botswana", timeZone: "Africa/Gaborone" },
  { key: "maseru", name: "Maseru", region: "Lesotho", timeZone: "Africa/Maseru" },
  { key: "mbabane", name: "Mbabane", region: "Eswatini", timeZone: "Africa/Mbabane" },
  { key: "antananarivo", name: "Antananarivo", region: "Madagascar", timeZone: "Indian/Antananarivo" },
  { key: "port-louis", name: "Port Louis", region: "Mauritius", timeZone: "Indian/Mauritius" },
  { key: "victoria-seychelles", name: "Victoria", region: "Seychelles", timeZone: "Indian/Mahe" },
  { key: "moroni", name: "Moroni", region: "Comoros", timeZone: "Indian/Comoro" },
  { key: "sao-tome", name: "São Tomé", region: "São Tomé and Príncipe", timeZone: "Africa/Sao_Tome" },
  { key: "malabo", name: "Malabo", region: "Equatorial Guinea", timeZone: "Africa/Malabo" },
  { key: "libreville", name: "Libreville", region: "Gabon", timeZone: "Africa/Libreville" },
  { key: "niamey", name: "Niamey", region: "Niger", timeZone: "Africa/Niamey" },
  { key: "ouagadougou", name: "Ouagadougou", region: "Burkina Faso", timeZone: "Africa/Ouagadougou" },
  { key: "bamako", name: "Bamako", region: "Mali", timeZone: "Africa/Bamako" },
  { key: "conakry", name: "Conakry", region: "Guinea", timeZone: "Africa/Conakry" },
  { key: "freetown", name: "Freetown", region: "Sierra Leone", timeZone: "Africa/Freetown" },
  { key: "monrovia", name: "Monrovia", region: "Liberia", timeZone: "Africa/Monrovia" },
  { key: "lome", name: "Lomé", region: "Togo", timeZone: "Africa/Lome" },
  { key: "porto-novo", name: "Porto-Novo", region: "Benin", timeZone: "Africa/Porto-Novo" },
  { key: "abuja", name: "Abuja", region: "Nigeria", timeZone: "Africa/Lagos" },
  { key: "nouakchott", name: "Nouakchott", region: "Mauritania", timeZone: "Africa/Nouakchott" },
  { key: "bissau", name: "Bissau", region: "Guinea-Bissau", timeZone: "Africa/Bissau" },
  { key: "praia", name: "Praia", region: "Cape Verde", timeZone: "Atlantic/Cape_Verde" },
  { key: "asmara", name: "Asmara", region: "Eritrea", timeZone: "Africa/Asmara" },
  { key: "nassau", name: "Nassau", region: "Bahamas", timeZone: "America/Nassau" },
  { key: "belize-city", name: "Belize City", region: "Belize", timeZone: "America/Belize" },
  { key: "san-salvador", name: "San Salvador", region: "El Salvador", timeZone: "America/El_Salvador" },
  { key: "tegucigalpa", name: "Tegucigalpa", region: "Honduras", timeZone: "America/Tegucigalpa" },
  { key: "managua", name: "Managua", region: "Nicaragua", timeZone: "America/Managua" },
  { key: "santo-domingo", name: "Santo Domingo", region: "Dominican Republic", timeZone: "America/Santo_Domingo" },
  { key: "port-au-prince", name: "Port-au-Prince", region: "Haiti", timeZone: "America/Port-au-Prince" },
  { key: "kingston", name: "Kingston", region: "Jamaica", timeZone: "America/Jamaica" },
  { key: "port-of-spain", name: "Port of Spain", region: "Trinidad and Tobago", timeZone: "America/Port_of_Spain" },
  { key: "georgetown-guyana", name: "Georgetown", region: "Guyana", timeZone: "America/Guyana" },
  { key: "paramaribo", name: "Paramaribo", region: "Suriname", timeZone: "America/Paramaribo" },
  { key: "la-paz", name: "La Paz", region: "Bolivia", timeZone: "America/La_Paz" },
  { key: "asuncion", name: "Asunción", region: "Paraguay", timeZone: "America/Asuncion" },
  { key: "brasilia", name: "Brasília", region: "Brazil", timeZone: "America/Sao_Paulo" },
  { key: "canberra", name: "Canberra", region: "Australia", timeZone: "Australia/Sydney" },
  { key: "honiara", name: "Honiara", region: "Solomon Islands", timeZone: "Pacific/Guadalcanal" },
  { key: "port-vila", name: "Port Vila", region: "Vanuatu", timeZone: "Pacific/Efate" },
  { key: "nukualofa", name: "Nuku'alofa", region: "Tonga", timeZone: "Pacific/Tongatapu" },
  { key: "apia", name: "Apia", region: "Samoa", timeZone: "Pacific/Apia" },
  { key: "tarawa", name: "Tarawa", region: "Kiribati", timeZone: "Pacific/Tarawa" },
  { key: "majuro", name: "Majuro", region: "Marshall Islands", timeZone: "Pacific/Majuro" },
  { key: "palikir", name: "Palikir", region: "Micronesia", timeZone: "Pacific/Pohnpei" },
  { key: "koror", name: "Koror", region: "Palau", timeZone: "Pacific/Palau" },
  { key: "funafuti", name: "Funafuti", region: "Tuvalu", timeZone: "Pacific/Funafuti" },
  { key: "noumea", name: "Nouméa", region: "New Caledonia", timeZone: "Pacific/Noumea" },
]
